config/routes.rb
Rails.application.routes.draw do
  
  #root "home#index"
  
  resources :pages
  get "/info/:permalink", to: "pages#show", as: :page_by_permalink
  resources :certificates
  resources :articles
  resources :home
  resources :products

  namespace :manage do
    root to: "products#index"
    get "/login" => "auth#new"
    post "/auth" => "auth#check"
    delete "/logout" => "auth#logout"

    resource :settings, only: [:edit, :update]
    resources :pages
    resources :certificates
    resources :articles
    resources :products
    resources :slides
  end
  root 'home#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_secure_password

  def self.god
    where(login: Rails.application.secrets.admin_login).first
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  mount_uploader :image, ArticleUploader

  validates :title, :subtitle, :content, :image, presence: true

  scope :sorted, -> { order(created_at: :desc) }
end

app/models/certificate.rb
class Certificate < ActiveRecord::Base
  mount_uploader :image, CertificateUploader
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :image, ProductUploader

  validates :title, :description, :image, presence: true

  scope :sorted, -> { order(created_at: :desc) }
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/models/slide.rb
class Slide < ActiveRecord::Base
  validates :image, presence: true
  
  mount_uploader :image, SlideUploader

  scope :sorted, -> {
    order(:position)
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :settings, :current_admin

  private

    def settings
      @settings ||= (Setting.last || Setting.create)
    end

    def current_admin
      @current_admin ||= Admin.where(id: session[:admin_id]).first if session[:admin_id]
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.sorted
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :image)
    end
end

app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController
  before_action :set_certificate, only: [:show, :edit, :update, :destroy]

  # GET /certificates
  # GET /certificates.json
  def index
    @certificates = Certificate.all
  end

  # GET /certificates/1
  # GET /certificates/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_certificate
      @certificate = Certificate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def certificate_params
      params.require(:certificate).permit(:title, :content, :image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @slides = Slide.sorted
    @products = Product.sorted.limit(3)
    @articles = Article.sorted.limit(3)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = if params[:permalink]
      Page.find_by(permalink: params[:permalink])
    else
      Page.find(params[:id])
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.sorted
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/certificates_helper.rb
module CertificatesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/application/_articles.html.erb
<% articles.in_groups_of 3 do |group| %>
  <div class="row article-row">
    <% group.compact.each do |article| %>
      <div class="col-sm-4 article-row__column">
        <%= render article %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/application/_certificates.html.erb
<% certificates.in_groups_of 3 do |group| %>
  <div class="row">
    <% group.compact.each do |certificate| %>
      <div class="col-sm-4">
        <%= render certificate %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/application/_link_to_all.html.erb
<%= link_to path, class: "link-to-all" do %>
  <span class="link-to-all__text"><%= text %></span>
  <span class="link-to-all__arrow">
    <%= image_tag "arrow.svg", width: 16, height: 30, class: "arrow-image" %>
  </span>
<% end %>

app/views/application/_products.html.erb
<% products.in_groups_of 3 do |group| %>
  <div class="row product-row">
    <% group.compact.each do |product| %>
      <div class="col-lg-4 product-row__column">
        <%= render product %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/application/_slider.html.erb
<div class="slider">
  <div class="swiper-container">
    <div class="swiper-wrapper">
      <%= render slides  %>
    </div>
  </div>

  <%= image_tag "arrow.svg", width: 32, height: 60, class: "slider__arrow slider__arrow--prev" %>
  <%= image_tag "arrow.svg", width: 32, height: 60, class: "slider__arrow slider__arrow--next" %>
</div>

app/views/articles/_article.html.erb
<%= link_to article, class: "article-item-link" do %>
  <div class="article-item">
    <%= image_tag article.image.url(:thumb), class: "article-item__image" if article.image.present? %>

    <div class="article-item__info">
      <h4 class="title">
        <%= article.title %>
      </h4>
      <h6 class="title title--sub">
        <%= article.subtitle %>
      </h6>
    </div>
  </div>
<% end %>

app/views/articles/index.html.erb
<div class="section-title">
  <div class="container">
    <h1 class="section-title__text">
      <%= title "Статьи" %>
    </h1>
  </div>
</div>

<div class="container">
  <%= render "articles", articles: @articles %>
</div>

app/views/articles/show.html.erb
<div class="article-show-header">
  <%= image_tag @article.image.url(:featured), class: "article-show-header__picture" if @article.image.present? %>
  <h1 class="article-show-header__title">
    <%= title @article.title %>
  </h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <div class="article-show-content">
        <%= simple_format(@article.content) %>
        <% description(@article.content) %>
      </div>
    </div>
  </div>
</div>

app/views/certificates/_certificate.html.erb
<%= link_to certificate, class: "certificate-item" do %>
	<div class="certificate-item__image">
		<%= image_tag certificate.image.url(:thumb), class: "certificate-image" %>
	</div>
	<h4 class="certificate-item__title">
		<%= certificate.title %>
	</h4>
<% end %>

app/views/certificates/index.html.erb
<div class="section-title">
  <div class="container">
    <h1 class="section-title__text">
      <%= title "Сертификаты" %>
    </h1>
  </div>
</div>

<div class="container">
  <%= render "certificates", certificates: @certificates %>
</div>

app/views/certificates/show.html.erb
<div class="section-title">
  <div class="container">
    <h1 class="section-title__text">
      <%= title @certificate.title.present? ? @certificate.title : "Сертификат" %>
    </h1>
  </div>
</div>

<div class="container">
  <div class="row">
    <% if @certificate.content.present? %>
      <div class="col-md-9">
        <%= image_tag @certificate.image.url(:featured), class: "img-fluid" %>
      </div>
      <div class="col-md-3">
        <div class="certificate-info-content">
          <%= simple_format(@certificate.content) %>
        </div>
      </div>
    <% else %>
      <div class="col-md-8 offset-md-2">
        <%= image_tag @certificate.image.url(:featured), class: "img-fluid" %>
      </div>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<div class="container">
  <%= render "slider", slides: @slides %>

  <div class="home-page-block">
    <%= render "products", products: @products %>

    <%= render "link_to_all",
          path: products_path,
          text: "Все продукты"
    %>
  </div>
</div>

<div class="section-title">
  <div class="container">
    <h2 class="section-title__text">
      Статьи, советы, полезная информация
    </h2>
  </div>
</div>

<div class="container">
  <div class="home-page-block">
    <%= render "articles", articles: @articles %>

    <%= render "link_to_all",
          path: articles_path,
          text: "Статьи, советы, полезная информация"
    %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="yandex-verification" content="c579a6034b3eeff9" />

    <%= csrf_meta_tags %>

    <%= title :site => "Dea Nature", :separator => '—', reverse: true %>
    <%= keywords :default => "deanature, dea nature, дея нейче, купить средства для омоложения, средства для омоложения, средства для похудения бишкек, купить средства для похудения в бишкеке, похудеть в бишкеке, купить клетчатку в бишкеке" %>
    <%= description :default => "Компания ОсОО Дея Нэйче существует на рынке в течении 10-ти лет (с декабря 2004 по декабрь 2009 года компания называлась ЧП Ханмурзина, с 2010 по декабрь 2013 года нас знали под названием ОсОО Клеона). В декабре 2013 года компания переименована в ОсОО Дея Нэйче, в переводе — Богиня-природа. 10 лет наша косметика, и продукты для похудения популярны и востребованы, потому что мы стараемся создавать новые уникальные продукты для похудения, продукты снижающие уровень глюкозы в крови для больных сахарным диабетом, а так же уникальные продукты для ухода за кожей лица и тела, тщательно подбирая самые эффективные гипоаллергенные, причем только натуральные ингредиенты. Принципиально не используем химические добавки и стероидные препараты. Поскольку большинство женщин обеспокоены лишним весом, признаками возрастных изменений и хотят надолго сохранить здоровье и молодость, мы работаем над созданием интенсивных действенных средств против набора лишнего веса, а как следствие старения организма. Наши продукты помогают женщинам чувствовать и выглядеть красивыми и уверенными в себе." %>

    <%= stylesheet_link_tag 'application', media: 'all'  %>
  </head>

  <body>
    <div class="app">
      <div class="main-header">
        <div class="container">
          <div class="row">
            <div class="col-md-3 main-logo">
              <%= image_tag('leaf.png', width: 153, height: 153, class: "main-logo__leaf") %>
              <%= link_to image_tag('logo.svg', width: 118, height: 58), root_path, class: "main-logo__sign" %>
            </div>
            <div class="col-md-9">
              <%= render_navigation %>
            </div>
          </div>
        </div>
      </div>

      <div class="app__container">
        <div class="container">
          <%= render_navigation context: :admin if current_admin %>
        </div>

        <%= yield %>
      </div>

      <footer class="main-footer">
        <div class="container main-footer__container">
          <div class="row">
            <div class="col-md-5">
              <%= render_navigation context: :footer %>
            </div>
            <div class="col-md-7">
              <div class="footer-contacts">
                <%= settings.address %><br />
                <%= mail_to settings.email %>
              </div>
            </div>
          </div>
          <%= link_to image_tag("lock.svg", width: 12, height: 12), manage_login_path, class: "footer-address__lock" unless current_admin %>
        </div>
      </footer>
    </div>

    <%= javascript_include_tag 'application' %>

    <% if Rails.env.development? %>
      <script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')</script>
    <% end %>
  </body>
</html>

app/views/layouts/manage.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="yandex-verification" content="c579a6034b3eeff9" />

    <%= csrf_meta_tags %>

    <%= title :site => "Панель управления Dea Nature", :separator => '—', reverse: true %>
    <%= stylesheet_link_tag 'application', media: 'all'  %>
  </head>

  <body>
    <div class="app">
      <div class="main-header">
        <div class="container">
          <div class="row">
            <div class="col-md-3 main-logo">
              <%= image_tag('leaf.png', width: 153, height: 153, class: "main-logo__leaf") %>
              <%= link_to image_tag('logo.svg', width: 118, height: 58), root_path, class: "main-logo__sign" %>
            </div>
            <div class="col-md-9">
              <%= render_navigation %>
            </div>
          </div>
        </div>
      </div>

      <div class="app__container">
        <div class="container">
          <%= render_navigation context: :admin if current_admin %>

          <%= yield %>
        </div>
      </div>

      <footer class="main-footer">
        <div class="container main-footer__container">
          <div class="row">
            <div class="col-md-5">
              <%= render_navigation context: :footer %>
            </div>
            <div class="col-md-7">
              <div class="footer-contacts">
                <%= settings.address %><br />
                <%= mail_to settings.email %>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>

    <%= javascript_include_tag 'application' %>

    <% if Rails.env.development? %>
      <script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')</script>
    <% end %>
  </body>
</html>

app/views/pages/show.html.erb
<div class="section-title">
  <div class="container">
    <h1 class="section-title__text">
      <%= title @page.title %>
    </h1>
  </div>
</div>

<div class="container">
  <%= simple_format(@page.content) %>
  <% description(@page.content) %>
</div>

app/views/products/_product.html.erb
<%= link_to product, class: "product-item-link" do  %>
  <div class="product-item">
    <%= image_tag product.image.url(:thumb), class: "product-item__picture" %>

    <div class="product-item__info">
      <h4 class="product-item__title--sub">
        <%= product.subtitle %>
      </h4>
      <h4 class="product-item__title">
        <%= product.title %>
      </h4>
    </div>
  </div>
<% end %>

app/views/products/index.html.erb
<div class="section-title">
  <div class="container">
    <h1 class="section-title__text">
      <%= title "Продукция" %>
    </h1>
  </div>
</div>

<div class="container">
  <%= render "products", products: @products %>
</div>

app/views/products/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="product-show-picture">
        <div class="product-show-picture__wrap">
          <%= image_tag @product.image.url(:featured), class: "img-fluid" %>
        </div>
      </div>

      <% if @product.nutritional_value.present? || @product.energy_value.present? || @product.weight.present? %>
        <ul class="product-show-options">
          <% if @product.nutritional_value.present? %>
            <li class="product-show-options__option">
              <span class="name">Пищевая ценность на 100 г продукта:</span>
              <span class="value"><%= @product.nutritional_value %></span>
            </li>
          <% end %>

          <% if @product.energy_value.present? %>
            <li class="product-show-options__option">
              <span class="name">Энергетическая ценность на 100 г продукта:</span>
              <span class="value"><%= @product.energy_value %></span>
            </li>
          <% end %>

          <li class="product-show-options__option">
            <span class="name">Масса:</span>
            <span class="value"><%= @product.weight %></span>
          </li>
        </ul>
      <% end %>
    </div>
    <div class="col-md-6">

      <h1 class="product-show-title">
        <%= title @product.title %>
      </h1>

      <div class="product-show-description">
        <%= simple_format(@product.description) %>
        <% description(@product.description) %>
      </div>
    </div>
  </div>

</div>

app/views/slides/_slide.html.erb
<%= link_to slide.link, target: "_blank", class: "swiper-slide slide" do %>
  <img data-src="<%= slide.image.url(:normal) %>" width="1110" height="420" class="swiper-lazy slide__image" />

  <% if slide.title.present? || slide.content.present? %>
    <div class="slide__content">
      <% if slide.title.present? %>
        <h3 class="title"><%= slide.title %></h3>
      <% end %>
      <% if slide.content.present? %>
        <div class="content">
          <%= slide.content %>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="swiper-lazy-preloader"></div>
<% end %>